// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbBpkSCLwy2p4dimBjXNh5XXIiQSz9FnI',
    appId: '1:657690570978:web:eb0213c719834e4a646ebb',
    messagingSenderId: '657690570978',
    projectId: 'kasie-transie-4',
    authDomain: 'kasie-transie-4.firebaseapp.com',
    storageBucket: 'kasie-transie-4.firebasestorage.app',
    measurementId: 'G-HH2PQG54B2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5AGxqLVyDNjRoRRDYVcnBq6_HMPAu3MU',
    appId: '1:657690570978:android:3ac7b42afcbc67db646ebb',
    messagingSenderId: '657690570978',
    projectId: 'kasie-transie-4',
    storageBucket: 'kasie-transie-4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBCW2jYebHUN609zOFxgTnm0JWP-1Y40s',
    appId: '1:854189510560:ios:5299ecd4460821b236dec5',
    messagingSenderId: '854189510560',
    projectId: 'kasie-transie-3',
    storageBucket: 'kasie-transie-3.appspot.com',
    iosClientId: '854189510560-6845bffb6d7pdvq48pe1luecbecumd7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.kasieTransieMarshal2',
  );

}